# Generated by Django 4.2 on 2023-04-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisito',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
