# Generated by Django 4.2 on 2023-04-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_requisito_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='completados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matricula',
            name='pendientes',
            field=models.IntegerField(default=0),
        ),
    ]
